/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelinContracts from "./openzeppelin-contracts";
export type { openzeppelinContracts };
import type * as openzeppelinContractsUpgradeable from "./openzeppelin-contracts-upgradeable";
export type { openzeppelinContractsUpgradeable };
import type * as safeContractsGit from "./safe-contracts.git";
export type { safeContractsGit };
