/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SignatureAllowance__factory } from "./SignatureAllowance__factory";
export { SignatureAllowanceStorage__factory } from "./SignatureAllowanceStorage__factory";
