/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as safeModule from "./SafeModule";
export type { safeModule };
import type * as signatureAllowance from "./SignatureAllowance";
export type { signatureAllowance };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { GM } from "./GM";
export type { MockToken } from "./MockToken";
