/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SignatureAllowance } from "./SignatureAllowance";
export type { SignatureAllowanceStorage } from "./SignatureAllowanceStorage";
