# This is workflow for workspace `contracts` at `./packages/contracts/`

name: Safe Signature Allowance

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [main]
    pull_request:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
              with:
                submodules: recursive
            - uses: CultureHQ/actions-yarn@v1.0.1
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: "18"
            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                version: nightly
              # Runs a single command using the runners shell
            - name: Installs needed packages using npm
              run: yarn install

    lint:
        runs-on: ubuntu-latest

        needs:
            build

            # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
              with:
                submodules: recursive
            - uses: CultureHQ/actions-yarn@v1.0.1
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: "18"

              # Runs a single command using the runners shell
            - name: Installs needed packages using npm
              run: yarn install

              # Runs a single command using the runners shell
            - name: Lints the project
              run: yarn lint

    test:
        runs-on: ubuntu-latest

        needs:
            build

            # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
              with:
                submodules: recursive
            - uses: CultureHQ/actions-yarn@v1.0.1
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: "18"
            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                version: nightly

              # Runs a single command using the runners shell
            - name: Installs needed packages using npm
              run: yarn install

              # Runs a single command using the runners shell
            - name: Tests the project
              run: yarn workspace contracts run test

    coverage:
        runs-on: ubuntu-latest

        needs:
            build

            # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
              with:
                submodules: recursive
            - uses: CultureHQ/actions-yarn@v1.0.1
            - uses: actions/setup-node@v3.5.1
              with:
                  node-version: "18"
            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                version: nightly

              # Runs a single command using the runners shell
            - name: Installs needed packages using npm
              run: yarn install

              # Runs a single command using the runners shell
            - name: Tests the project
              run: yarn workspace contracts run coverage
